name: CMake

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'reports/**'
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'reports/**'
      - 'docs/**'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        artifact: [ "llp" ]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2

      - name: Build llp
        run: |
          cmake -B ${{github.workspace}}/llp/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}/llp
          cmake --build ${{github.workspace}}/llp/build --config ${{env.BUILD_TYPE}}
      
      - name: Build examples
        run: |
          cmake -B ${{github.workspace}}/examples/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}/examples
          cmake --build ${{github.workspace}}/examples/build --config ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-llp
          path: examples/build/bin/*/*
          retention-days: 1
      
      - name: test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} 
  create_release:
    name: "Prelease"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ubuntu-latest-llp
            macos-latest-llp
            windows-latest-llp


