name: CMake

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'reports/**'
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'reports/**'
      - 'docs/**'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.cxx_compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            cxx_compiler: g++-10
          - os: ubuntu-latest
            cxx_compiler: clang++
          - os: macos-latest
            cxx_compiler: clang++
          - os: windows-latest
            cxx_compiler: msbuild
          - os: windows-latest
            cxx_compiler: x86_64-w64-mingw32-g++
            generator: '-G "MinGW Makefiles"'
        artifact: [ "llp" ]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        if: matrix.os == 'windows-latest'
        with:
          platform: x64

      - name: Build llp
        run: |
          cmake -B ${{github.workspace}}/llp/build ${{matrix.generator}} -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}/llp
          cmake --build ${{github.workspace}}/llp/build --config ${{env.BUILD_TYPE}}

      - name: Build examples
        run: |
          cmake -B ${{github.workspace}}/examples/build ${{matrix.generator}} -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}/examples
          cmake --build ${{github.workspace}}/examples/build --config ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.cxx_compiler }}-llp
          path: examples/build/bin/*/*
          retention-days: 1

      - name: test
        working-directory: ${{github.workspace}}/llp/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
  create_release:
    name: "Prelease"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ubuntu-latest-llp
            macos-latest-llp
            windows-latest-llp


